### ISSUE TITLE
Any reason for PHP 5.3

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft.skeleton#2]
Is there any reason, that we require "tombzombie/dice": "dev-PHP5.3"?

**Comment by k00ni** [comment]
Because its a good DI solution and i thought we want to ship Saft.skeleton with a ready to use environment.

**Comment by white-gecko** [comment]
Yes, right. But sorry I think my question was not phrased correctly, it was regarding the exact version not the DI-framework-selection
