### ISSUE TITLE
Default Language in PropertyHelper

### ISSUE THREAD

**Issue by simeonackermann** [SaftIng/Saft.skeleton#3]
Currently it seems there is no way to set the default or preferred language for titles in `AbstractIndex`.

May it should defined in `TitleHelperIndex`

**Comment by k00ni** [comment]
We can pre-define English as default language. That definition should be located in AbstractIndex via a simple language tag or something like that. 

Extended classes such as TitleHelperIndex are basically a container for preferred properties.

**Comment by k00ni** [comment]
Fixed in #5.
