### ISSUE TITLE
Load PropertyHelper action from yaml

### ISSUE THREAD

**Issue by simeonackermann** [SaftIng/Saft.skeleton#4]
Prior we had the possibility to load actions (`createindex` or `fetchvalues`) from YAML file. 

Shall we implement the Yaml-Parser in the [PropertyHelper](https://github.com/SaftIng/Saft.example/tree/master/PropertyHelper) examples?

**Comment by k00ni** [comment]
I think the RequestHandler could be extended for that. What is your preferred way of handling languages? Per request (fetchvalues) or fixed (given in the constructor)?

**Comment by simeonackermann** [comment]
I would prefer to give the language as request parameter on fetch values

**Comment by simeonackermann** [comment]
I decided to don't implement a YAML parser to the `RequestHandler` for several reasons. (We can discuss it later ;) )

We also had the case, that fetched titles (payload), comes from a file. But I think such local file accesses are not the job for the Request Handler. It should be done by the caller, e.g. index.php, which creates the request from that data.

**Comment by k00ni** [comment]
Is this finished?

**Comment by simeonackermann** [comment]
Yes I thinks we can close this. I implemented the yaml parser to read the cache config data to create the RequestHandler. I think this is the better way.
